/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin_lab;

import com.util.FormUtil;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class list extends javax.swing.JInternalFrame {
Connection cnn;
ResultSet rss;
Statement stt;
    /**
     * Creates new form list
     */
    public list() {
        initComponents();
        tabel_hardware();
        tabel_software();
        FormUtil.centerWindow(this);
    }

    public void konek(){
        try{
        Class.forName("com.mysql.jdbc.Driver");
       cnn = DriverManager.getConnection("jdbc:mysql://localhost:3306/maintenes","root","");
        stt = cnn.createStatement();
         }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"gagal koneksi","pesan",JOptionPane.ERROR_MESSAGE);
    }
     }
    
     public void tabel_hardware(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("id ruang");
        tbl.addColumn("id komputer");
        tbl.addColumn("spesifikasi");
        tbl.addColumn("hdd");
        tbl.addColumn("ram");
        tbl_hardware.setModel(tbl);
        try{
            konek();
        String sql = "select * from tbl_komputer";
        stt=cnn.createStatement();
        rss = stt.executeQuery(sql);
        while (rss.next()){
        tbl.addRow(new Object[]{
        rss.getString(1),
        rss.getString(2),
        rss.getString(3),
        rss.getString(4),
        rss.getString(5)});
        tbl_hardware.setModel(tbl);
        }
        }catch (Exception e){
        System.out.println(e.getMessage());
          }
      }
     
     public void tabel_software(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("id komputer");
        tbl.addColumn("windoes");
        tbl.addColumn("antivirus");
        tbl.addColumn("web");
        tbl.addColumn("office");
        tbl_soft.setModel(tbl);
        try{
            konek();
        String sql = "select * from tbl_software";
        stt=cnn.createStatement();
        rss = stt.executeQuery(sql);
        while (rss.next()){
        tbl.addRow(new Object[]{
        rss.getString(1),
        rss.getString(2),
        rss.getString(3),
        rss.getString(4),
        rss.getString(5)});
        tbl_soft.setModel(tbl);
        }
        }catch (Exception e){
        System.out.println(e.getMessage());
          }
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_hardware = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_soft = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tbl_hardware.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_hardware);

        jTabbedPane1.addTab("list hardware", jScrollPane1);

        tbl_soft.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_soft);

        jTabbedPane1.addTab("list software", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("list software");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl_hardware;
    private javax.swing.JTable tbl_soft;
    // End of variables declaration//GEN-END:variables
}
